# Generated by Django 5.2.6 on 2025-10-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Jersey', 'Jersey'), ('Sepatu Bola', 'Sepatu Bola'), ('Bola', 'Bola'), ('Peralatan Latihan', 'Peralatan Latihan'), ('Aksesoris', 'Aksesoris'), ('Merchandise Klub', 'Merchandise Klub'), ('Lainnya', 'Lainnya')], default='OTH', max_length=60),
        ),
    ]
